site_name: phu
theme:
  name: material
  features:
    # - navigation.instant
    - content.code.copy
  feature:
    navigation.tabs: false
  # Use custom logo (shown in navbar) and favicon (small browser/tab icon)
  # logo: imgs/v03-phu-logo-small.svg
  # Optional dark-mode logo (Material supports this)
  # logo_dark: imgs/v03-phu-logo-small-fordark.svg
  code:
    # highlight_theme: "github"
    palette:
      - scheme: default
        primary: blue-grey
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - scheme: slate
        primary: blue-grey
        accent: amber
        toggle:
          icon: material/white-balance-sunny
          name: Switch to light mode

# Top-level favicon (path is relative to docs/)
# favicon: imgs/v01-phu-favicon.svg

# Repository metadata
repo_name: camilogarciabotero/phu
repo_url: https://github.com/camilogarciabotero/phu
edit_uri: edit/main/docs/

# Essential markdown extensions only
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: material/github
      link: https://github.com/camilogarciabotero/phu
    - icon: material/book-open-variant
      link: https://camilogarciabotero.github.io/phu/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            separate_signature: true
            docstring_style: numpy
            extra:
              paths: [src]

nav:
  - Home: index.md
  - Commands:
      - commands/cluster.md
      - commands/simplify-taxa.md
      - commands/screen.md