# .github/workflows/docs.yml
name: docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # <-- allow pushing to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # <-- avoid using checkout's token

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v3

      - run: uv pip install --system -U mkdocs mkdocs-material "mkdocstrings[python]"
      - run: mkdocs build --strict

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # Optional safety nets:
          # publish_branch: gh-pages   # (default)
          # force_orphan: true         # create branch if first deploy