name: docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v3

      # Create and "activate" a local .venv (activation not needed with uv)
      - run: uv venv
      - run: uv pip install -U mkdocs mkdocs-material "mkdocstrings[python]"

      # Run inside the venv via uv (no 'source' needed)
      - run: uv run mkdocs build --strict

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}